Add missing package so the MVP runs as described
After doing setup via:

```sh
cp options.example.js options.mine.js
npm install
cd public
bower install
```

And then attempting to run via:

```sh
node mvp-app.js
```

This change corrects the following **error**:
```
Seneca Fatal Error
==================

Message: The mail plugin failed to initialize: Cannot find module 'nodemailer-smtp-transport'.

Code: plugin_init

Stack: 
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at initTransport (/Users/jim/projects/seneca-test/mvp/node_modules/seneca-mail/mail.js:100:23)
    at Seneca.<anonymous> (/Users/jim/projects/seneca-test/mvp/node_modules/seneca-mail/mail.js:121:5)
    at Object.execspec.fn (/Users/jim/projects/seneca-test/mvp/node_modules/seneca/lib/seneca.js:1442:24)
    at Object._onImmediate (/Users/jim/projects/seneca-test/mvp/node_modules/seneca/lib/executor.js:93:14)
    at processImmediate [as _immediateCallback] (timers.js:345:15)

Instance: Seneca/0.5.21/72nsbo2tmoq2/1416969894673/-

When: 2014-11-26T02:44:55.362Z

Log: [sys,seneca,0.5.21,72nsbo2tmoq2/1416969894673/-,plugin_init,The mail plugin failed to initialize: Cannot find module 'nodemailer-smtp-transport'.,{options={},callback=,history=[{module=/Users/jim/projects/seneca-test/mvp/node_modules/seneca/lib/seneca.js,path=mail},{module=/Users/jim/projects/seneca-test/mvp/node_modules/seneca/lib/seneca.js,path=seneca-mail}],name=mail,search=[{type=normal,name=mail},{type=normal,name=seneca-mail},{type=normal,name=./mail},{type=normal,name=./seneca-mail}],modulepath=/Users/jim/projects/seneca-test/mvp/node_modules/seneca/lib/seneca.js,requirepath=seneca-mail,found={type=normal,name=seneca-mail},fullname=mail,tag=,service=,plugin_error=Cannot find module 'nodemailer-smtp-transport'}]

Node: { http_parser: '1.0', node: '0.10.33', v8: '3.14.5.9', ares: '1.9.0-DEV', uv: '0.10.29', zlib: '1.2.3', modules: '11', openssl: '1.0.1j' }

Process: pid=65126, path=/Users/jim/.nvm/v0.10.33/bin/node, args=[ 'node', '/Users/jim/projects/seneca-test/mvp' ]


connections property is deprecated. Use getConnections() method
2014-11-26T02:44:55.537Z	72nsbo2tmoq2/1416969894673/-	INFO	listen	3333
2014-11-26T02:44:55.655Z	72nsbo2tmoq2/1416969894673/-	INFO	plugin	admin	-	ACT	fpcxkquuavs7	admin	user	admin	9ebmxbja0b
2014-11-26T02:44:55.662Z	72nsbo2tmoq2/1416969894673/-	INFO	plugin	transport	-	ACT	zjgs4cyh4ak9	listen	{type=web,port=10101,host=0.0.0.0,path=/act,protocol=http,timeout=32778,msgprefix=seneca_,callmax=111111,msgidlen=12,role=transport,hook=listen}
Terminated at 2014-11-26T02:44:55.680Z. See above for error report.
```